version: '3.8'
services:
  db:
    image: 'mysql:8.0'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: mixer
      MYSQL_PASSWORD: 2222
      MYSQL_DATABASE: ai_farm_stay
    ports:
      - "3306:3306"
    volumes:
      - "./database/data:/var/lib/mysql"

  api-farm:
      image: ai-farm-stay-back-end  
      ports: 
        - "8050:8050" 
      volumes: 
        - ".:/app" 
      depends_on: 
        - db 
      links: 
        - "db:database"
